### PR TITLE
Restore support for Ruby 2.4

### LINKED ISSUE #252: Add required_ruby_version to gemspec? 2.3.0 release is broken on Ruby < 2.5
Hey there! 👋 

I just noticed that the recently-released version 2.3.0 uses the rescue-inside-a-block syntax that was added on Ruby 2.5.

```ruby
$ ruby -v && ruby -e "[].each do; rescue; end"
ruby 2.5.9p229 (2021-04-05 revision 67939) [x86_64-darwin19]
$ ruby -v && ruby -e "[].each do; rescue; end"
ruby 2.4.10p364 (2020-03-31 revision 67879) [x86_64-darwin19]
-e:1: syntax error, unexpected keyword_rescue, expecting keyword_end
[].each do; rescue; end
                  ^
```

This can be observed by running the test suite on Ruby 2.4:

```ruby
$ bundle exec rake
rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb

An error occurred while loading spec_helper.
Failure/Error: require "racecar/consumer"

SyntaxError:
  /racecar/lib/racecar/consumer.rb:76: syntax error, unexpected keyword_rescue, expecting keyword_end
            rescue Rdkafka::AbstractHandle::Wait
                  ^
  /racecar/lib/racecar/consumer.rb:76: syntax error, unexpected =>
  actHandle::WaitTimeoutError => e
                                ^
  /racecar/lib/racecar/consumer.rb:83: syntax error, unexpected keyword_rescue, expecting keyword_end
            rescue Rdkafka::RdkafkaError => e
                  ^
  /racecar/lib/racecar/consumer.rb:83: syntax error, unexpected =>
  escue Rdkafka::RdkafkaError => e
                                ^
  /racecar/lib/racecar/consumer.rb:123: syntax error, unexpected keyword_end, expecting end-of-input
    end
       ^
# ./lib/racecar.rb:7:in `require'
# ./lib/racecar.rb:7:in `<top (required)>'
# ./spec/spec_helper.rb:4:in `require'
# ./spec/spec_helper.rb:4:in `<top (required)>'
No examples found.
No examples found.


Finished in 0.00004 seconds (files took 0.1608 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

Finished in 0.00004 seconds (files took 0.1608 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples

rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
```

I'd like to request the addition of [`required_ruby_version = '>= 2.5'` to the gemspec](https://guides.rubygems.org/specification-reference/#required_ruby_version), thus enabling rubygems to avoid using this newer version on older Rubies.

Let me know if you'd like me open a PR with the change, I'd be glad to 😄 

Additionally, it'd be extra nice if you yanked version 2.3.0 and released a 2.3.1 with this change, thus allowing older Rubies to never try to pick version 2.3.0 😉 

Thanks, and have an awesome day!

P.s.: For context, I work at @Datadog our Ruby APM gem [`ddtrace`](https://github.com/DataDog/dd-trace-rb), which also supports integrating with `racecar`, and our CI runs regularly with older Rubies as well, as we have customers still using them 🚀

### PR DESCRIPTION
**Pull request by ivoanjo**
The "ensure inside a block without an explicit begin/end" feature is a Ruby 2.5 feature (see <https://bugs.ruby-lang.org/issues/12906>) and its usage broke racecar usage on Ruby 2.4 (#252).

By re-adding the begin/end, it all works again. To make sure it keeps working, I've also added Ruby 2.4 to the test matrix on
GitHub.

I also added a `spec.required_ruby_version` to the gemspec, to make it clear which versions are tested. I tried checking if Ruby 2.3 or older could be trivially supported, but in fact the `rdkafka` dependency also requires 2.4+ and thus it implicitly sets the minimum bound for racecar.

This is an alternative to #256.

Fixes #252

P.s: I've included the version bump, let me know if you'd prefer that I remove it.

### CODE REVIEW

File: lib/racecar/version.rb [hunk 1]
```diff
@@ -1,5 +1,5 @@
 # frozen_string_literal: true
 
 module Racecar
-  VERSION = "2.3.0"
+  VERSION = "2.3.1"
```
Comment (dasch) [inline lib/racecar/version.rb:4]: Please revert this change, I will handle the version bump separately.

**Review by dasch — APPROVED** [review]
Thanks! Can you rebase on master?

**Comment by ivoanjo** [comment]
@dasch done :)

**Comment by dasch** [comment]
Can you fix the specs? Think you need to bundle install or something.

**Comment by ivoanjo** [comment]
Oops, sorry for the confusion, I had missed that the CI needed an up-to-date `Gemfile.lock`. Also realized I had missed a `"` in the yaml versions list.

Hopefully it's ok now :)

**Comment by dasch** [comment]
Tests are failing:

```
Fetching gem metadata from https://rubygems.org/......
  activesupport-6.0.3.4 requires ruby version >= 2.5.0, which is incompatible with
  the current version, ruby 2.4.10p364
```

**Comment by ivoanjo** [comment]
I've added a version restriction to the `Gemfile` in adbd222, as well as rebased on top of current master.

Is there a way for me to run the CI tests easily? All of these changes usually don't affect running the tests locally, and hence I'm somewhat dependent on waiting for the CI run to come back.

**Comment by dasch** [comment]
Github has a thing where the maintainer needs to approve workflows until the author has committed to master or something...

**Comment by dasch** [comment]
Thanks!

**Comment by ivoanjo** [comment]
> Github has a thing where the maintainer needs to approve workflows until the author has committed to master or something...

Ah... Mumble mumble something about abusers making the rest of us not have nice things :)

---

My pleasure, thanks for the patience as well! :)
